services:
  postgres:
    image: postgres:16-alpine
    container_name: regi-volley-postgres
    environment:
      POSTGRES_DB: regi_volley
      POSTGRES_USER: regi_volley
      POSTGRES_PASSWORD: regi_volley
    ports:
      - "5432:5432"
    volumes:
      - regi-volley-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regi_volley"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  regi-volley-postgres-data:
